# API gateway should start in port 9000.
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
# The API Gateway should have the following routes defined:
# - userservice (Eureka Service Registry serviceId: user-service)
# - gymservice (Eureka Service Registry serviceId: gym-service)
# - enquiryservice (Eureka Service Registry serviceId: enquiry-service)
# - ticketservice (Eureka Service Registry serviceId: ticket-service)
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"

server:
  port: 9000
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  zipkin:
    base-url: http://localhost:9411/

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    user-service:
      path: /userservice/**
      serviceId: user-service
      stripPrefix: true
    gym-service:
      path: /gymservice/**
      serviceId: gym-service
      stripPrefix: true
    enquiry-service:
      path: /enquiryservice/**
      serviceId: enquiry-service
      stripPrefix: true
    ticket-service:
      path: /ticketservice/**
      serviceId: ticket-service
      stripPrefix: true
