# service should start with port number 8092. mongodb database name and
# port number should be accepted using environment variable
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"


server:
  port: 8092
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
spring:
  data:
    mongodb:
      uri: mongodb://localhost/goldysgym #${MONGO_URI}
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: enquiry.new.exchange
    routingKey: enquiry.new.routingKey
  zipkin:
    base-url: http://localhost:9411/
logging:
  file:
    path: /logs/sr
test: val