# server should start with port number 8090. MySQL database config parameters
# should be accepted using environment variable
# It should connect to the Zipkins container running using the URL "http://localhost:9411/"
#
# This service should register with Eureka Service Registry running in "http://localhost:8761/"

server:
  port: 8090

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb # ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # ${MYSQL_USERNAME}
    password: root # ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect